//login
POST https://terminales.puertobuenosaires.gob.ar:8086/login
Content-Type: application/json

{
    "USUARIO": "emanuel.zarate@trp.com.ar",
    "CLAVE": "123456"
}
//consulta LDE
GET http://10.10.0.223:8086/LDE/MAEU6363989
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU1VBUklPIjoidHJwX3dlYnNlcnZpY2VzX2FncEB0cnAuY29tLmFyIiwiQ0xBVkUiOiJQNGcwM2wzY3RyMG4xYzAiLCJUWVBFIjoiIiwiaWF0IjoxNTExNDY2Njc4LCJleHAiOjE1MTE1NTMwNzh9.2inZT08nLuh8I-tKYqUvE4cv0KDFwrLyFwiVsDFUseA

//login
POST http://10.10.0.223:8086/login
Content-Type: application/json

{
    "USUARIO": "dreyes@puertobuenosaires.gob.ar",
    "CLAVE": "123456"
}
//insertar LDE
POST https://terminales.puertobuenosaires.gob.ar:8086/lde
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU1VBUklPIjoiZHJleWVzQHB1ZXJ0b2J1ZW5vc2FpcmVzLmdvYi5hciIsIkNMQVZFIjoiMTIzNDU2IiwiVFlQRSI6IiIsImlhdCI6MTUxMTg4MTMyNywiZXhwIjoxNTExODgxMzg3fQ.JABnjg1siHJNwYI5ZLPwwWmn9H4-VfIKGZ5oN7Tn_1c

{"TERMINAL":"TRP",
"BUQUE":"TEST VESSEL",
"VIAJE":"101S",
"CONTENEDOR":"SUDU6718868",
"BL":"N7515A5KR330",
"FECHA_DEV":"2017-12-30",
"LUGAR_DEV":"TRP",
"CUIT":"30593435810",
"EMAIL":"dreyes@puertobuenosaires.gob.ar",
"ID_CLIENTE":"920910735a"}

//consulta LDE
GET https://terminales.puertobuenosaires.gob.ar:8086/LDE/SUDU6718868
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU1VBUklPIjoiZW1hbnVlbC56YXJhdGVAdHJwLmNvbS5hciIsIkNMQVZFIjoiMTIzNDU2IiwiVFlQRSI6IiIsImlhdCI6MTUxMTg4MTQwMiwiZXhwIjoxNTExODgxNDYyfQ.btlNydI1uNprTV4jwy49aNV9hm8e23cJuQq9mN0pNkU
//cambio lugar devolucion
PUT https://terminales.puertobuenosaires.gob.ar:8086/lde/lugar
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU1VBUklPIjoiZHJleWVzQHB1ZXJ0b2J1ZW5vc2FpcmVzLmdvYi5hciIsIkNMQVZFIjoiMTIzNDU2IiwiVFlQRSI6IiIsImlhdCI6MTUxMTU1Mjk5OSwiZXhwIjoxNTExNTUzMDU5fQ.9xvPWWZGVAScSg28xYeYRjX6e0YNtIjKFdo7vhvcM78

{"CONTENEDOR": "SUDU6718864",
"LUGAR_DEV":"TRP",
"FECHA_DEV":"2017-12-30",
"ID_CLIENTE":"920910735",
"ID": "59f6ad832da8973769378fa2",
"EMAIL": "dreyes@puertobuenosaires.gob.ar"
}